name: 'Dependency Review'
on: [pull_request]

permissions:
  contents: read
  pull-requests: write

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
        
      # Run snapshot
      - name: Run action
        uses: ./
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
        
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
        with:
          comment-summary-in-pr: true
